### PR TITLE
new: brakemen: ignore Ruby 2.7.4 EOL

### PR DESCRIPTION
**Pull request by vladimir-mencl-eresearch**
Pre-requisite for mergning #273 (to get tests to pass).

### CODE REVIEW

**Comment by vladimir-mencl-eresearch** [comment]
@ArthurZheng if you could please review and merge - required to get tests passing for #273....

**Review by ArthurZheng — APPROVED** [review]
Thanks @vladimir-mencl-eresearch, sorry I was away yesterday.

**Comment by ArthurZheng** [comment]
Can anyone @ausaccessfed/developers  with write access please approve this PR. Thank you!
Screen Shot 2023-03-14 at 7 29 46 am

**Review by waldofouche — APPROVED** [review]

**Comment by vladimir-mencl-eresearch** [comment]
Apologies, I *again* forgot to sign the commit.  Force-pushed as signed commit now.

But while fiddling with this PR, I disabled auto-merge and I don't have permission to turn it on again - can someone please merge this now?

**Comment by ArthurZheng** [comment]
No worries at all @vladimir-mencl-eresearch , all done

**Pull request merged**
