### PR TITLE
Feature sessions source

### PR DESCRIPTION
**Pull request by vladimir-mencl-eresearch**
Hi @smangelsdorf 

As discussed in #176, here's the promised feature.

It adds the concept of a selectable session data source throughout the code base - the session data source can either point to DiscoveryServiceEvent or FederatedLoginEvent.

Key highligths are:
* I had to add make FederatedLoginEvent support the same functions as DiscoveryLoginEvent does - this was done by adding scope and foreign key definitions to FederatedLoginEvent.
  * I did not have to add the attribute aliases - I instead got round by parameterizing the `idp_sessions` / `sp_sessions` queries.
* On the report form, users can select the session source
* This selection gets passed through the controllers to report constructor objects.
* An installation can be configure the site-wide default for the selection (and in the absence of the setting, it defaults to 'DS')
* The public reports have no form and only use the site-wide default
* Report subscriptions carry the source with them (as per the form that generated the reports).
  * ... and so it's possible to subscribe to the same report twice, with different sources...
  * and the source the subscription is tied to is displayed on the Subscriptions list
  * This also means I've had to add a migration to add the source column to automated_reports.
  * And for reports that need_source?, the `source` parameter is required
  * So for some admin reports, I had to hide the Subscribe button if source is not set in the context - i.e., only display the Subscribe button after the report form is submitted and the report is rendered.
* And I've added another migration to add an index to federated_login_events to improve performance.
* An AutomatedReports object validates that source is set only iff report_class is a report that needs a source - that makes it tighter but makes correct tests slightly more tedious (and may complicate data migration - see below)
* Because source can now be either DS or IdP, I've removed the `'AAF Discovery Service'` references from the report title pages
* And I've instead added the source being used to the report title itself.  Does not look particularly great - I'm happy to adjust if you suggest a different place in the report where to state the source used.
* I have updated all tests and get a clean pass.
* And Rubocop gives me a clean pass two.

Please let me know whether you're happy to merge this or whether you have any concerns to be resolved.

Possible issues I see:
* Code coverage is not 100% - there are two uncovered code paths
* One is in AutomatedReport.source_if_needed?  - which would return the site-wide default for report subscriptions created before this is introduced.  I'd like to hear your opinion on how to handle this - whether to convert all NULL source values (where needs_source? == true) to site-wide default (or 'DS') - or whether to leave database with objects that may not validate.  If updating the database, we might actually remove the use of the default from this line that otherwise never gets hit.
* Another uncovered line is in the `scope` I added on FederatedLoginEvent - because the tests do not exercise the IdP session source properly.  Would you have a recommendation on how to adjust the tests to run over `source` ranging over `[ 'DS', 'IdP' ]` ?
* The change I did to add the source to report title are not seen for  TabularReports yet - because tabular reports do not display the title yet.  I have not found may way through the javascript code yet to make the title visible (which I'd consider a generic bugfix).  I can add it to this PR (some pointers on where to look would be appreciated), but I'd also wait for you feedback on putting the data source name into the report titles (as I see adding the source as another subtitle as another feasible option)

How's the PR looking to you?

Cheers,
Vlad

### CODE REVIEW

**Comment by vladimir-mencl-eresearch** [comment]
@smangelsdorf : I see this PR has conflicts with changes brought in #175 create a merge conflict: I'll down-merge from current HEAD (develop) to resolve the conflict.

**Comment by smangelsdorf** [comment]
Thanks @vladimir-mencl-eresearch, sorry about the conflict.

**Comment by vladimir-mencl-eresearch** [comment]
@smangelsdorf No worries - this was easy to resolve.  Merge commit is in and I get the green label above again :-)

**Comment by vladimir-mencl-eresearch** [comment]
Hi @smangelsdorf , any estimate when this would get reviewed...? Cheers, Vlad

**Comment by smangelsdorf** [comment]
@vladimir-mencl-eresearch: Thanks for following up. I've completed the initial review, and save for one remaining Rubocop violation, I'm happy with the approach / implementation.

I'd like to see the missing test coverage addressed before this is merged, but I've not yet had time to experiment / understand how to respond to the questions you raised in your PR description. It's definitely on my todo list.

**Comment by vladimir-mencl-eresearch** [comment]
Hi @smangelsdorf , thanks for the feedback - pleased to hear that.

Apologies about the rubocop violation: I accidentally introduced that when resolving the merge conflict with your other changes - fixed now.

I look forward to hearing from you once you have suggestions for completing the code coverage - happy to add that based on your instructions.

Cheers,
Vlad

**Comment by vladimir-mencl-eresearch** [comment]
Hi @smangelsdorf ,  FYI, I'll be going on rather long leave in about 4 weeks time.  Just giving you a heads-up so that we have enough time to complete the interaction on this PR before I go...

I'm so far waiting on your input to complete the code coverage - please let me know if you have any suggestions...

Cheers,
Vlad

**Comment by smangelsdorf** [comment]
Thanks for the heads up. I've had some time-sensitive tasks to attend to this month, and haven't yet had the time to figure out how to test the new code in this PR. I'm expecting to get to it soon.

**Comment by smangelsdorf** [comment]
* `AutomatedReport#source_if_needed`

    You can cover this using a model test. You can simulate missing configuration by mocking, e.g.:

    ```ruby
    before do
      allow(Rails.application.config)
        .to receive_message_chain(:reporting_service, :default_session_source)
        .and_return(nil)
    end
    ```

* `FederatedLoginEvent.within_range` scope

   You can cover this explicitly using a model test, though I agree it would be nicer to cover it via the report classes as well to ensure the integration is all working.

    The best place to start would be with a single report. For example, the `DailyDemandReport` tests look reasonably simple. I'd take the following approach:

    1. Duplicate one of the existing `context` blocks. I'd start with `context 'when events are sessions with response'`
    2. Refactor the context to use IdP events rather than DS events, and get that test working
    3. Compare the refactored version to the original, and look for a way to parameterise it based on source. The two parts that I think would need to be parameterised are creating the test data and running the report
    4. Try to apply the same refactoring across the reports that have dual sources

* Title on tabular reports

    Could you please log this as an issue so it can be addressed in a future PR? This PR is broad enough in scope already and I don't want to delay its merge too long, since it's already been sitting for a while.

I hope this helps.

**Comment by vladimir-mencl-eresearch** [comment]
Thanks for the pointers, @smangelsdorf !

I've been able to cover AutomatedReports - I've added a few test to describe the validation rules I added, and I've specifically described the source_if_needed method.  Together with your trick for hiding the config file, that gets me to 100% coverage on that file.

I've also looked at DailyDemandReport  spec.  I've been able to get a copy of the test running, but I could not figure out how to parameterize a test to run with two (or more) different parameters - how to iterate over a range *for the whole test*.

The closest I got to turn the reusable parts of the test into a shared_examples section, and then add two separate tests with separate parameters using these examples.

I'm pasting below what I got to - is this the right way to do it?

I'm afraid this would make the spec code rather messy - so checking with you before I commit it and apply the same pattern to other reports.

Having it done just for DailyDemandReport would give us coverage over the IdP sessions code - but would make this report's spec inconsistent with the rest.  Your thoughts on this?

Regarding report titles: agree to track the title on tabular reports separately; will create an issue for that.  Are you otherwise fine with how I added the session source into the report title?

Cheers,
Vlad

PS: And I also had to add a missing factory for FederatedLoginEvents - just pushed that in; heavily based on the DiscoveryServiceEvents factory.

**Comment by vladimir-mencl-eresearch** [comment]
And this is how I got the tests working...

```
--- /tmp/daily_demand_report_spec.rb	2017-06-23 16:26:44.321076974 +1200
+++ spec/reports/daily_demand_report_spec.rb	2017-06-23 16:24:38.206410644 +1200
@@ -16,66 +16,91 @@
   let(:days_count) { ((finish - start).to_i / 86_400).to_i }

   let(:range) do
     { start: start.strftime('%FT%H:%M:%S%z'),
       end: finish.strftime('%FT%H:%M:%S%z') }
   end

   let(:identity_provider) { create :identity_provider }
   let(:service_provider) { create :service_provider }

-  subject { DailyDemandReport.new(start, finish, 'DS') }
+  subject { DailyDemandReport.new(start, finish, source) }

   let(:report) { subject.generate }
   let(:data) { report[:data] }

   def expect_in_range
     (0..86_340).step(300).each_with_index do |t, index|
       expect(data[:sessions][index]).to match_array([t, value])
     end
   end

-  context 'when events are sessions with response' do
-    before do
-      create_list :discovery_service_event, 5, :response,
-                  selected_idp: identity_provider.entity_id,
-                  initiating_sp: service_provider.entity_id
-    end
+  # sources = %w[DS IdP]
+  # source_names = { 'DS' => 'Discovery Service', 'IdP' => 'IdP Event Log' }

+  shared_examples 'a report procesing events from the selected source' do
     let(:value) { anything }

     it 'should include title, units and labels' do
-      output_title = title + ' (Discovery Service)'
+      output_title = title + ' (' + source_name + ')'
       expect(report).to include(title: output_title, units: units,
                                 labels: labels, range: range)
     end

     it 'sessions are response types generated within given range' do
       expect_in_range
     end
   end

+  context 'when events are sessions with response' do
+    before do
+      create_list :federated_login_event, 5, :OK,
+                  asserting_party: identity_provider.entity_id,
+                  relying_party: service_provider.entity_id
+    end
+
+    let(:source) { 'DS' }
+    let(:source_name) { 'Discovery Service' }
+
+    it_behaves_like 'a report procesing events from the selected source'
+  end
+
+  context 'when events are IdP sessions' do
+    before do
+      create_list :federated_login_event, 5, :OK,
+                  asserting_party: identity_provider.entity_id,
+                  relying_party: service_provider.entity_id
+    end
+
+    let(:source) { 'IdP' }
+    let(:source_name) { 'IdP Event Log' }
+
+    it_behaves_like 'a report procesing events from the selected source'
+  end
+
   context 'when events are not responded' do
+    let(:source) { 'DS' }
     before do
       create_list :discovery_service_event, 20,
                   initiating_sp: service_provider.entity_id,
                   timestamp: 1.day.ago.beginning_of_day
     end

     let(:value) { 0.00 }

     it 'should not count any sessions' do
       expect_in_range
     end
   end

   context 'when events timestamps are specified manually' do
+    let(:source) { 'DS' }
     before :example do
       [*1..5].each do |n|
         create :discovery_service_event, :response,
                selected_idp: identity_provider.entity_id,
                initiating_sp: service_provider.entity_id,
                timestamp: n.days.ago.beginning_of_day

         create :discovery_service_event, :response,
                selected_idp: identity_provider.entity_id,
                initiating_sp: service_provider.entity_id,
```

**Comment by smangelsdorf** [comment]
@vladimir-mencl-eresearch: Yes, that looks like a good start, though I definitely hear what you're saying about making the test cases messy.

You might be able to reduce the duplication/coupling if you find a way to parameterise the factory, perhaps something like this might help:

```ruby
shared_examples '..' do
  before { 5.times { create_event(1.day.ago) } }
  # ...
end

context 'with discovery service events' do
  def create_event(timestamp)
    create_list :federated_login_event, 5, :OK,
                asserting_party: identity_provider.entity_id,
                relying_party: service_provider.entity_id,
                timestamp: timestamp
  end

  context 'when the events are responses' do
    # ...
  end

  context 'when the events are requests' do
    # ...
  end
end

context 'when events are IdP responses' do
  def create_event(timestamp)
    create :discovery_service_event, :response,
           selected_idp: identity_provider.entity_id,
           initiating_sp: service_provider.entity_id,
           timestamp: timestamp
  end

  # ... (from memory, there's no "request" phase logged in F-TICKS data)
end
```

We tend to err on the side of messy tests and clean production code. If good test coverage means a bit of duplication, that's alright. The alternative is that we deploy with a bug which could've been picked up by testing.

**Comment by vladimir-mencl-eresearch** [comment]
Thanks for the feedback, @smangelsdorf !

I'm now trying to figure out how to actually close this off....

I see your suggestion removes the clutter a small step - there's only one "before", but the create event would still have to exist separately in the DS and IdP branches.  So the test code complexity / messiness looks about the same to me.

I'm not sure whether to stop at just daily_demand_report_spec, or do apply this to more tests... (I interpret your last paragraph as asking for more tests, even if that means being messy in test code).

I can see several ways forward:
1. I commit the code I had pasted above
2. I redo the code with your suggestion (split "before" code into create_event)
3. I redo the code with the above split and also apply the same change to more tests: federated_sessions_report_spec.rb, and maybe also 
```
identity_provider_daily_demand_report_spec.rb
identity_provider_destination_services_report_spec.rb
identity_provider_sessions_report_spec.rb
identity_provider_utilization_report_spec.rb
service_provider_daily_demand_report_spec.rb
service_provider_sessions_report_spec.rb
service_provider_source_identity_providers_report_spec.rb
service_provider_utilization_report_spec.rb
```

Your pick?

Cheers,
Vlad

**Comment by smangelsdorf** [comment]
Given the sweeping changes, I think option 3 is the best path forward, though I recognise that it's a bit of extra work. My only issue with this as it stands is that without testing it manually in my browser, I can't be sure that the `source` argument is being respected for every report. As you'll have seen, we've put a lot of effort into making sure the reports are tested thoroughly.

The other alternative is the unwritten option 4, which is that my refactoring suggestion might not work out or you might have a better idea which ensures all the reports are tested. I'll leave it with you.

**Comment by vladimir-mencl-eresearch** [comment]
Hi @smangelsdorf 

Sure - I do not want to get your code base to a level where you'd be uncomfortable with the insufficient level of testing.  I appreciate all the effort you've put into the tests.

So, to come to a suitable set of tests, I think I could:
* Implement option 3 as per above - for all the classes listed
* Test that Source selection gets passed through.  In `spec/features/administrator_reports_spec.rb`, I see a lot of `"viewing Report"` scenarios that so far just fill in the start and end date and expect to see a report.  I could add an additional expectation on this report using the source (e.g., based on the report title).
* the same could be done to `spec/features/identity_provider_reports_spec.rb` and `spec/features/service_provider_reports_spec.rb`
* To test subscriptions also carry over `source`,  I could also parameterize tests in `spec/features/automated_report_instances_spec.rb` and check that `viewing automated_report_instances#show` sees the source name in the title of the generated report.
* And I might also add tests to `spec/features/automated_reports_spec.rb` to confirm the Session Data Source is correctly showing up on the Subscriptions page.

With all of the above added to tests, would you be comfortable about the test coverage?

Cheers,
Vlad

**Comment by smangelsdorf** [comment]
Sounds good to me.

**Comment by vladimir-mencl-eresearch** [comment]
Done first part of the list (option 3 from the previous discussion).

Number of examples went up from 840 to 894.

Going on with the rest.

**Comment by vladimir-mencl-eresearch** [comment]
Created #178 to track the title in the tabular reports separately.

Added points 2 and 3 from my list.  As these depend on seeing the title, for tabular reports, as a workaround for #178, I am instead checking for the raw report data in the page.  That still meets the purpose of the test - confirms the right session source was selected.

Two last points from the list to go...

**Comment by vladimir-mencl-eresearch** [comment]
And the last two are now in as well.  And a Rubocop fix.

@smangelsdorf , I've added all the tests we agreed on.  Please let me know if you're now happy to merge this or if you need anything else from me.  Cheers, Vlad

**Comment by vladimir-mencl-eresearch** [comment]
Expanded to 915 examples now....

**Comment by vladimir-mencl-eresearch** [comment]
@smangelsdorf - just checking if you've been able to review the additional tests I added and whether you're happy with the PR now...

**Comment by smangelsdorf** [comment]
Thanks @vladimir-mencl-eresearch

**Pull request merged**
