### PR TITLE
Revert `execJS` gem to `2.7.0`

### PR DESCRIPTION
**Pull request by waldofouche**
For details on this issue, refer here: https://github.com/ausaccessfed/stockpile/issues/89

This is part of https://github.com/ausaccessfed/stockpile/issues/87

### CODE REVIEW

**Comment by vladimir-mencl-eresearch** [comment]
Happy to confirm this fixes #240 .

**Comment by waldofouche** [comment]
Hi @vladimir-mencl-eresearch thanks for your message, I will merge this PR for you now. It should fix any issues caused by `execJS`. As your other message stated https://github.com/ausaccessfed/reporting-service/issues/240#issuecomment-903333547

> is the intention to expect that server will have nodejs installed?

Yes. We are planing on including a NodeJS runtime on the server to be installed through a docker container. For the moment we will just run the old version until we are able to get the project containerized.

**Review by ArthurZheng — APPROVED** [review]
👍

**Comment by vladimir-mencl-eresearch** [comment]
Thanks for the quick fix -  and I'll watch out for when you switch to external `nodejs`.

**Pull request merged**
